### ISSUE TITLE
Feature: add supports the multiple configurations

### ISSUE THREAD

**Issue by chkpnt** [webdiscus/html-bundler-webpack-plugin#101]
In the README it's noted that this plugin can't be used with [multiple config files](https://github.com/webdiscus/html-bundler-webpack-plugin?tab=readme-ov-file#multiple-config-files). I don't know if it is the same, but in my setup that the plugin can't be used with an exported [multiple configuration](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations) (single file, but multiple configurations), too.

**Comment by webdiscus** [comment]
@chkpnt Thanks for the feature request.
I will add supports for multiple configurations.

**Comment by webdiscus** [comment]
@chkpnt 

The support the multiple configurations has been added in the next major version - `4.0.0-beta.0`.
Can you please test this beta version with your use case.

**Comment by chkpnt** [comment]
I've just tested 4.0.0-beta.0 with my `webpack.config.cjs` consisting of three configurations and it's working great. :-) Many thanks for the quick realization!
