### ISSUE TITLE
Respect realContentHash option and calculate real contenthash

### ISSUE THREAD

**Issue by wielski** [webdiscus/html-bundler-webpack-plugin#12]
## Current behaviour

Plugin does not respect `realContentHash: true`.
`[contenthash]` in filename is always wrong, because of minimization and optimization is called after assets declaration.

## Expected behaviour

`[contenthash]` should be md4 of css / js output, and should be calculated at last optimization step.

### Reproduction Example

Add `optimization: { realContentHash: true }`, build something, and check real hash of file.

## Environment

- OS: macOS 
- version of Node.js: 16.10
- version of Webpack: 5.82.1
- version of the Plugin: 1.18.0

## Additional context

This is important for artefacts testing.
I fixed it by custom plugin, that calculates hash at very last step, but this is too hackish.
It will be much better if real contenthash will be added to plugin by default

```
compiler.hooks.compilation.tap('ApplyHTMLBundlerHashFixPlugin', (compilation) => {
  compilation.hooks.processAssets.tapPromise({ name: `html-bundler-webpack-plugin`, stage: Infinity }, () => {
    for (assetName in compilation.assets) {
      if (assetName.endsWith('.css') || assetName.endsWith('.js')) {
        const asset = compilation.getAsset(assetName);
        const source = asset.source.source();
        const hash = webpack.util.createHash('md4')
        hash.update(source);
        const digest = hash.digest('hex').slice(0, 20);
        const newAssetName = assetName.replace(/(\.[a-z0-9]{20})\./, `.${digest}.`);
        compilation.renameAsset(assetName, newAssetName);
        compilation.updateAsset(newAssetName, asset.source, {
          ...asset.info,
          contenthash: digest,
        });
      }
    }

    return Promise.resolve();
  });
});
```

**Comment by webdiscus** [comment]
Hi @wielski,

thanks for the report.

I know that `contenthash` is not a real content hash. For performance reasons, the hash is not updated in the last step.
Some CSS libraries, such as bootstrap, are very large and slow down performance drastically.

If the real hash of the content is important, then perhaps this will be implemented later.

**Comment by wielski** [comment]
@webdiscus 
thanks for your response.

Real content hash is important for me, cause our team have a practice to test everything, even artifact of build.
It's hard to test correctness of build if content hash is random.

It would be great to have option for enabling this.

**Comment by webdiscus** [comment]
Hello @wielski,

in version `2.12.0` I added the `integrity` attribute for JS and CSS.
I once again took a deep dive into the hashing process in Webpack.

Now 100% real hashed names are generated. The proof of this is that the integrity hash is generated based on the real hash of the final file content and the file name is generated based on the same hash. All tests with Integrity passed and the browser loads JS and CSS with valid `integrity` value only.

But this does not guarantee the constant generation of the same hashed names for the same content.

### Why?
Webpack works asynchronously and some internal modules are created in a random sequence, therefore different IDs are created in the runtime code parts, which naturally changes the content and, accordingly, the hash.

Here is an example of JS code compiled by Webpack:
```js
(self.webpackChunk=self.webpackChunk||[]).push([[457],{815:(e,i,t)=>{const u=t(117),s=t(667) ....
```
As you can see, the `457`, `815`, `117`, etc are random IDs (depending on the sequence of async processes).

I noticed that hashes change while the content remains the same if the webpack version or some of its plugins are updated.
The same goes for CSS. If you update sass or sass-loader, the hash for many CSS files also changes.
I myself struggle with updating the expected hashed file names of tests after each package update.

### How to fix?

No solution.
I use concrete version (w/o leading `^`) of modules package.json to keep the same package versions on the testing server:
```js
{
  "devDependencies": {
    ...
    "css-loader": "6.8.1",
    "sass": "1.67.0",
    "sass-loader": "13.3.2",
    "webpack": "5.88.2",
    ...
 }
}
```
