### ISSUE TITLE
Two html file use same href reference cause Can't resolve  Exception

### ISSUE THREAD

**Issue by mikeshimura** [webdiscus/html-bundler-webpack-plugin#122]
## Current behaviour
If I set two href save filename then cause error.
index.html
<link rel="apple-touch-icon" href="./logo2.svg"/>
example.html
<link rel="apple-touch-icon" href="./logo2.svg"/>

PluginException:
 HTML Bundler Plugin  Can't resolve C:\a\wkreact\react2\src\logo2.svg in the file src\example.html

    at resolveException (C:\a\wkreact\react2\node_modules\html-bundler-webpack-plugin\src\Plugin\Messages\Exception.js:133:9)
    at Resolver.require (C:\a\wkreact\react2\node_modules\html-bundler-webpack-plugin\src\Plugin\Resolver.js:276:5)
    at C:\a\wkreact\react2\src\example.html:1:382

If I set different filename then okay.
index.html
<link rel="apple-touch-icon" href="./logo2.svg"/>
example.html
<link rel="apple-touch-icon" href="./logo3.svg"/>

## Expected behaviour
same filename cause no error.

### Reproduction

- [x ] repository URL git@github.com:mikeshimura/react2.git
- please use bundler.prod.config.js as config
- [ ] example code

## Environment

- OS: [macOS, Linux, Windows]
- windows 11
- version of Node.js: v22.11.0
- version of Webpack:5.96.1
- version of the Plugin:4.5.0

## Appreciation for the useful project

- [ ] After the problem is resolved, do not forget to give a star ⭐

**Comment by mikeshimura** [comment]
If I set two href save filename then cause error.
index.html
\<link rel="apple-touch-icon" href="./logo2.svg"/>
example.html
\<link rel="apple-touch-icon" href="./logo2.svg"/>

Error.
If I set different filename then okay.
index.html
\<link rel="apple-touch-icon" href="./logo2.svg"/>
example.html
\<link rel="apple-touch-icon" href="./logo3.svg"/>
Okay.

**Comment by webdiscus** [comment]
Hello @mikeshimura,

thanks for the issue report.
I will fix it.

**Comment by mikeshimura** [comment]
Hello webdiscus,

Thank you very much for your quick response.
I tried and trouble resolved.

Much appreciated.

Masanobu Shimura


2024年11月26日(火) 20:30 webdiscus ***@***.***>:

**Comment by webdiscus** [comment]
@mikeshimura 

yet one tip...

You can use the HMR for CSS. After changes a CSS file (imported in one JS) the changes will be displayed in browser without reload.

```js
new HtmlBundlerPlugin({
  // define HTML files here to hold all relevant setting at one place
  entry: {
      index: './src/index.html',  // => dist/index.html
      example: './src/example.html', // => dist/example.html
      // ...
  },
  js: {
    filename: 'js/[name].[contenthash:8].js',
  },
  css: {
    filename: 'css/[name].[contenthash:8].css',
    hot: true, // <= enable Hot Update CSS in browser without full reload
  },
}),
```
