### ISSUE TITLE
v.4.6 Missing Dependencies

### ISSUE THREAD

**Issue by vralle** [webdiscus/html-bundler-webpack-plugin#123]
## Current behaviour
After update the plugin to v.4.6 webpack build task fails with error:
`[webpack-cli] Error: Cannot find module 'parse5'`

### Reproduction

- [ ] repository URL
- [ ] example code

## Environment

- OS: Debian 12.8
- version of Node.js: 22.9.0, npm 10.9.1
- version of Webpack: 5.97.0
- version of the Plugin: 4.6

## Additional context
Ok, are dependencies optional? I've got installed `parse5` and had another error:
`ERROR in ./src/views/home.html
Module build failed (from ./node_modules/html-bundler-webpack-plugin/src/Loader/index.js):
LoaderException: 
 HTML Bundler Plugin  Loader initialisation failed.
File: src/views/home.html
Error: 
[filter] The required markdown-it module not found. Please install the module: npm i -D markdown-it`
home.html has pure html and eta templates Here I stopped. I had a rollback of html-bundler-webpack-plugin to v.4.5.3 and all Ok.

## Appreciation for the useful project

- [ ] After the problem is resolved, do not forget to give a star ⭐

**Comment by webdiscus** [comment]
Hello @vralle,

thanks for the issue report.
In `v4.6.0` added support for including `*.md` files in templates, which requires additional modules.
I will fix it.

**Comment by webdiscus** [comment]
@vralle 
the issue is fixed in the `v4.6.1`. 
Can you please test it? 

Thank you!

**Comment by vralle** [comment]
It was fast. With version 4.6.1 everything is OK. Thanks
