### ISSUE TITLE
[FEATURE REQUEST] Tags in report

### ISSUE THREAD

**Issue by vralle** [webdiscus/html-bundler-webpack-plugin#125]
Webpack report may contain handler tags.
Here is an example.
![Screenshot 2024-12-04 122224](https://github.com/user-attachments/assets/6349896f-bde8-41fb-92e1-1806a385d9b7)
The example on the screenshot used `css-minimizer-webpack-plugin`, `copy-webpack-plugin` and my own plugin for purged CSS.

**What is motivation or use case for adding/changing the behavior?**

On my example I can quickly verify that assets have been minimized, styles were purged. This is convenient and helps to avoid unnecessary testing.

## Feature request
**Describe the solution you'd like**

Add tags to report if HTML entries are successfully processed by minimizer.

I haven't investigated how HTML minification is implemented in the plugin.
The standard implementation involves adding a label to 'AssetInfo' object and then using 'compilation.hooks.statsPrinter' hook.
```js
async process(compiler, compilation, assets) {
  const content = makeSomething();
    compilation.updateAsset(
            file,
            new RawSource(content),
            { minimized: true },
          );
}
apply(compiler) {
    const { pluginName } = this;

    compiler.hooks.compilation.tap(pluginName, (compilation) => {
      compilation.hooks.processAssets.tapPromise(
        {
          name: pluginName,
          stage: compiler.webpack.Compilation.PROCESS_ASSETS_STAGE_OPTIMIZE_SIZE,
          additionalAssets: undefined,
        },
        (assets) => this.process(compiler, compilation, assets),
      );

      compilation.hooks.statsPrinter.tap(pluginName, (stats) => {
        stats.hooks.print
          .for('asset.info.minimized')
          .tap(
            pluginName,
            (minimized, { green, formatFlag }) => {
              if (!minimized) {
                return '';
              }

              if (!green || !formatFlag) {
                return 'minimized';
              }

              return (green)((formatFlag)('minimized'));
            },
          );
      });
    });
  }
```

**Describe alternatives you've considered**

## Appreciation for the useful project

- [ ] After the feature is implemented, do not forget to give a star ⭐

**Comment by webdiscus** [comment]
@vralle 

Thanks for the feature request. It's very important to have correct asset info.
In my intern test, I can add `minimized` property in  the `assetInfo` on the HTML file.

In the `compiler.hooks.done` hook I will see the updated asset info in `stats.compilation.assetsInfo`, e.g.:
```
 ## DONE:  Map(3) {
      'index.html' => { javascriptModule: false, minimized: true, size: 198 }, <= HERE is added the 'minimized' property
      'style.47f4da55.css' => { size: 21 },
      'main.5317c1f6.js' => {
        immutable: true,
        contenthash: '5317c1f6',
        javascriptModule: false,
        minimized: true, // <= this is set by Webpack in production mode
        size: 23
      }
    }
```

But, I can't reproduce the `stats.hooks.print.for('asset.info.minimized')` hook. It just doesn't work by me.

Can you please create small repo with working `stats.hooks.print.for('asset.info.minimized')` hook.

**Comment by webdiscus** [comment]
@vralle 

ah, the `stats.hooks.print.for('asset.info.minimized')` works only when webpack run in CLI.
My problem was using integration test, where Webpack run via API.

![image](https://github.com/user-attachments/assets/fa9b7aeb-15d8-4b13-be7d-cd9cbef6646f)

I will finish new version tomorrow.

**Comment by webdiscus** [comment]
@vralle

the feature is implemented. Can you please try the `v4.8.0`
