### ISSUE TITLE
Callback onBeforeRender

### ISSUE THREAD

**Issue by 5ulo** [webdiscus/html-bundler-webpack-plugin#28]
## Feature request

**What is motivation or use case for adding/changing the behavior?**
Would be great to have callbacks like for example `onBeforeRender` where I can manipulate data from json and render them after some changes etc.

**Describe the solution you'd like**

`HandlebarsPlugin` has severa callbacks - `onBeforeSetup`, `onBeforeRender`, `onBeforeSave`, `onDone`. I bet in your plugin are they too but aren't accessible.
- `onBeforeSetup` - this was the point to register custom helpers - this plugin does it inside `preprocessorOptions`
- `onBeforeRender` - this is what I am interested in - good for replacements inside json data file. 
```JSON
{
    "replacements": {
        "[sitename]": "ACME"
    },
    "meta": {
        "name": "ACME",
        "description": "",
    },
    "page": {
        "home": {
            "title": "Welcome to [sitename] website",
            "title_alt": "Welcome to {{meta.name}} website"
        }
    }
}
```
Imagine you have website name which can be used all across the website and also in text like `Welcome to [sitename] website` which in this example should return as `Welcome to ACME website`. Or instead would be great to use it like `Welcome to {{meta.name}} website` - this though is obviously not working.
- `onBeforeSave` - I used this to manipulate dir/file structure - this plugin handles it in `preprocessorOptions`
- `onDone` - I havent never used

**Describe alternatives you've considered**

I haven't found any alternative yet. Only write the full string manually.

**Comment by webdiscus** [comment]
Hello @5ulo 

## 1. onBeforeRender

yes, that makes sense to implement:
`beforePreprocessor` - called right before `preprocessor` with the same attributes:

```js
{
  beforePreprocessor: (
    template: string,
    loaderContext: LoaderContext<Object> & { data: { [k: string]: any } | string }
  ) =>  null | string
  preprocessor: 'handlebars'
}
```
where `loaderContext.data` is your loaded/passed JSON, what can be modified.

## 2. Helpers registration onBeforeSetup

The plugin does not allow you to register  helpers, since it does it itself. You can write helpers code, but registeration makes the plugin. 

The plugin watch changes in helpers and updates modified helpers self, therefore it's impossible to allow registration of helpers outside the plugin code.

You can add all helpers from a dir or define a helper as JS code. What is your special requirement for registration?

## 3. onBeforeSave
To  manipulate dir/file structure you can use the `filename` option as the function:
```js
{
  filename: (PathData) => {
     return 'custom/path/custom-file.html'
  }
}
```
What is your special requirement for manipulate with output HTML filename?

P.S.
The `beforePreprocessor` options will be added in the next release.

Тhank you for participating in the development of the plugin.

**Comment by 5ulo** [comment]
Sorry for missleading description. I was interested only to `onBeforeRender`. The other callbacks were mentioned just as an example what callbacks are implemented in `HandlebarsPlugin`. Therefore I wrote the notice to `onBeforeSetup` and `onBeforeSave` that this and that functionality is done inside the `preprocessorOptions` which is absolutely perfect.
So again.. only the `onBeforeRender` (`beforePreprocessor` as you found the solution :)).. every other callback is just up to you or if someone can find some usable reason to have them.

**Comment by webdiscus** [comment]
@5ulo 

the new [beforePreprocessor](https://github.com/webdiscus/html-bundler-webpack-plugin/issues/28#loader-option-before-preprocessor) callback option is added in the `v2.13.0`.

**Comment by 5ulo** [comment]
That was fast.. I tested it and it kinda works. My data are in json file where the replacements are at the very beginning of the json. So I have to modify the full data. This is how I do it:
```javascript
beforePreprocessor: (template, { resourcePath, data }) => {

    let newData = data;
    function _escapeForRegex(string) {
        return string.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    }
    const { replacements, ...restData } = newData; // deconstruc the json to replacements and the rest
    let dataAsString = JSON.stringify(restData); // make text from rest of the data
    Object.keys(replacements).map((key) => { // replacements for every item in replacements
        dataAsString = dataAsString.replace(new RegExp(_escapeForRegex(key), 'g'), replacements[key]);
    });
    newData = JSON.parse(dataAsString); // back to json

    data = newData; // this returns the new data but wont apply them to the template - [sitename] not replaced
    // data.section = newData.section;  // if I replace only section object the new data are applied to the template - [sitename] is replaced
    console.log(data); // returns the full replaced data which is expected - see [sitename] replaced
},
```
Any idea how to replace the old data to fully modified data? Because I don't know where the placeholders like `[sitename]` would be used so I can't rely on applying the replace only to `data.section`.
thanks

**Comment by webdiscus** [comment]
@5ulo 

the `data` is the local destructed reference to the `loaderContext.data` object.
If you assign the `data = newData`, you override the the reference to `newData` and the `data` contains not more reference to the original `loaderContext.data` object.

You should use the parent object `loaderContext`:


```js
beforePreprocessor: (template, loaderContext) => {
   const { resourcePath, data } = loaderContext;

    function _escapeForRegex(string) {
        return string.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    }

    const { replacements, ...restData } = data;
    let dataAsString = JSON.stringify(restData);
    Object.keys(replacements).map((key) => {
        dataAsString = dataAsString.replace(new RegExp(_escapeForRegex(key), 'g'), replacements[key]);
    });

    loaderContext.data = JSON.parse(dataAsString); // <= set the property data in the loaderContext object
},
```

**Comment by 5ulo** [comment]
That makes sense but the output to template are the original untouched data.
`console.log(loaderContext.data)` returns the modified data though.

**Comment by webdiscus** [comment]
@5ulo 

Sorry, I had the wrong code example. I have tested your case and I get an error in console.
it's very strange that you didn't have the error:

```
[html-bundler-webpack-plugin]  beforePreprocessor failed.
TypeError: Cannot set property data of #<Object> which has only a getter
```

Also, the Webpack `Loader Interface` has the  `read-only` `data` property, therefore you can't set the `data` directly in the `loaderContext`. I forgot this, sorry for confusing you.

But, there is the workaround with 3 code lines:

```js
const {  loaderIndex, resourcePath, data } = loaderContext; // 1) <= destruct the `loaderIndex`
const loaderObject = loaderContext.loaders[loaderIndex]; // 2) <= get the reference to loaderObject

loaderObject.data = newData; // 3) <= set your new data object to the `data` of the `loaderObject`
console.log(loaderContext.data); // => output changed data
```

**Comment by webdiscus** [comment]
@5ulo, the `beforePreprocessor` code example above is fixed and should now works.

**Comment by 5ulo** [comment]
Thanks, that was it! Closing this as it is working and also pasting jere the full working `beforePreprocessor` code just in case:
```javascript
beforePreprocessor: (template, loaderContext) => {
    const {  loaderIndex, resourcePath, data } = loaderContext; // 1) <= destruct the `loaderIndex`
    const loaderObject = loaderContext.loaders[loaderIndex]; // 2) <= get the reference to loaderObject

    function _escapeForRegex(string) {
        return string.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    }
    
    const { replacements, ...restData } = data;

    let dataAsString = JSON.stringify(restData);
    Object.keys(replacements).map((key) => {
        dataAsString = dataAsString.replace(new RegExp(_escapeForRegex(key), 'g'), replacements[key]);
    });

    loaderObject.data = JSON.parse(dataAsString);  // 3) <= set your new data object to the `data` of the `loaderObject`
},
```

**Comment by 5ulo** [comment]
Thanks, that was it! Closing this as it is working and also pasting jere the full working `beforePreprocessor` code just in case:
```javascript
beforePreprocessor: (template, loaderContext) => {
    const {  loaderIndex, resourcePath, data } = loaderContext; // 1) <= destruct the `loaderIndex`
    const loaderObject = loaderContext.loaders[loaderIndex]; // 2) <= get the reference to loaderObject

    function _escapeForRegex(string) {
        return string.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    }
    
    const { replacements, ...restData } = data;

    let dataAsString = JSON.stringify(restData);
    Object.keys(replacements).map((key) => {
        dataAsString = dataAsString.replace(new RegExp(_escapeForRegex(key), 'g'), replacements[key]);
    });

    loaderObject.data = JSON.parse(dataAsString);  // 3) <= set your new data object to the `data` of the `loaderObject`
},
```
