### ISSUE TITLE
How can I keep the original `.php` file extension?

### ISSUE THREAD

**Issue by webdiscus** [webdiscus/html-bundler-webpack-plugin#4]
### Discussed in https://github.com/webdiscus/html-bundler-webpack-plugin/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **Raxel21** March 21, 2023</sup>
Hi, I hope everything is going well for you, today I discovered your plugin and I find it very useful.

Well, I am having a problem working with `.php`, with `.html` it works perfectly. I tried to adapt the code but I did not succeed. 

I tried 2 ways

It works, but it changes the extension to `.html`, so it breaks the PHP code.
```javascript
new HtmlBundlerPlugin({
  test: /\.php$/i,
  verbose: true,
  entry: {
    index: path.join(__dirname, 'src', 'public', 'index.php'),
  },
  js: {
    filename: '[name].[contenthash:8].js',
  },
  css: {
    filename: '[name].[contenthash:8].css',
  },
})
```
So I tried this other way 

It also works, but it keeps changing the extension to `.html`, but this time I get an error:
`html-bundler-webpack-plugin: Failed to execute the template function`
I thought that just returning the template in the `preprocessor` line would work but I get the above error.
```javascript
new HtmlBundlerPlugin({
  test: /\.php$/i,
  verbose: true,
  entry: {
    home: {
      import: path.join(__dirname, 'src', 'public', 'index.php'),
      filename: 'index.php',
    },
  },
  js: {
    filename: '[name].[contenthash:8].js',
  },
  css: {
    filename: '[name].[contenthash:8].css',
  },
  loaderOptions: {
    preprocessor: (template, { data }) => template,
  },
})
``` 
Any suggestions please. Or maybe I forgot something from the documentation?
**Thank you in advance** </div>

**Comment by webdiscus** [comment]
The plugin expects an HTML output file, but not PHP.
I will add support for a custom output file.

**Comment by Raxel21** [comment]
**Thank you in advance for your time**

**Comment by webdiscus** [comment]
@Raxel21 

in the new release `v1.9.0` the issue is fixed. Now  a PHP template can be processed.

```js
new HtmlBundlerPlugin({
  test: /\.php$/i,
  verbose: true,
  filename: '[name].php', // define output filename for all templates defined in entry 
  entry: {
    home: path.join(__dirname, 'src/public/index.php'),
  },
  js: {
    filename: '[name].[contenthash:8].js',
  },
  css: {
    filename: '[name].[contenthash:8].css',
  },
  loaderOptions: {
    preprocessor: false, // disable template compilation to HTML
  },
})
```

Please see [How to process a PHP template](https://github.com/webdiscus/html-bundler-webpack-plugin#recipe-preprocessor-php) in readme.

**Comment by Raxel21** [comment]
Thank you so much, It works so good! Thank you for taking the time to add this new functionality.

**Comment by webdiscus** [comment]
@Raxel21 

is the problem solved?  Can be the issue closed?

**Comment by Raxel21** [comment]
**Yes, it works very well for me, thank you very much!**
