### ISSUE TITLE
Writing own adapter for responsive-loader

### ISSUE THREAD

**Issue by webdiscus** [webdiscus/html-bundler-webpack-plugin#40]
I really liked custom adapters in [responsive-loader](https://github.com/dazuaz/responsive-loader/tree/master#writing-your-own-adapter). I think I would be happy with tools like this in the HTML Bundler Plugin.

**Comment by vralle** [comment]
> Writing own adapter for responsive-loader
It's not correct. I don't have issue with the responsive-loader and its adapters)

**Comment by webdiscus** [comment]
> It's not correct. I don't have any issues for the responsive-loader and its adapters)

it was new question ;-)
You can create new discussion or issue for a question, no problem :-)

**Comment by webdiscus** [comment]
@vralle 

did you know that the plugin can work with this responsive-loader?

Here is an example: [How to resize and generate responsive images](https://github.com/webdiscus/html-bundler-webpack-plugin/issues/40#how-to-resize-and-generate-responsive-images)

Here are many test cases:
- [responsive-images-html-css](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/master/test/cases/responsive-images-html-css)
- [responsive-images-html-css-js](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/master/test/cases/responsive-images-html-css-js)
- and many other...

What exactly is stopping you from writing an adapter for the loader?

**Comment by vralle** [comment]
Ok. I stopped using this plugin. Responsive Images and [Imagemin Webpack](https://github.com/webpack-contrib/image-minimizer-webpack-plugin#imagemin-webpack) have compatibility issues. I settled on the latter, so it covers 100% of the necessary operations with images.
Here is last adapter I used
```js
// @ts-check

const sharp = require('sharp');

const args = require('../../args');

class SharpAdapter {
  /** @type {sharp.Sharp} */
  image;

  /** @param {string} imagePath */
  constructor(imagePath) {
    this.image = sharp(imagePath);
  }

  /** @returns {Promise<sharp.Metadata>} */
  metadata() {
    return this.image.metadata();
  }

  /**
   * @param {ResizeProps}
   * @returns {Promise<{ data: Buffer; width: number; height: number }>}
   */
  resize({ width, mime, options }) {
    console.log('load Sharp adapter with options:', options);
    return new Promise((resolve, reject) => {
      let resized = this.image.clone().resize(width, null);
      if (!options.rotate) {
        // .toBuffer() strips EXIF metadata like orientation, so portrait
        // images will become landscape. This updates the image to reflect
        // the EXIF metadata (if an EXIF orientation is set; otherwise unchanged).
        resized.rotate();
      }
      if (options.background) {
        resized = resized.flatten({
          background: options.background,
        });
      }

      if (mime === 'image/jpeg') {
        resized = resized.jpeg(args.sharpConfig.jpeg);
      }

      if (mime === 'image/png') {
        resized = resized.png(args.sharpConfig.png);
      }

      if (mime === 'image/webp') {
        resized = resized.webp(args.sharpConfig.webp);
      }

      // rotate
      if (options.rotate && options.rotate !== 0) {
        resized = resized.rotate(options.rotate);
      }

      resized.toBuffer((err, data, { height }) => {
        if (err) {
          reject(err);
        } else {
          resolve({
            data,
            width,
            height,
          });
        }
      });
    });
  }
}

/**
 * @param {string} imagePath
 * @returns {SharpAdapter}
 */
module.exports = (imagePath) => new SharpAdapter(imagePath);

```

**Comment by webdiscus** [comment]
> Ok. I stopped using this plugin.
Ok.

**Comment by webdiscus** [comment]
@vralle 

here is the usage example [image-minimizer](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/beta/examples/image-minimizer) of the image-minimizer-webpack-plugin

It works with images in HTML, CSS and in JS.

With Bundler Plugin can be used every loaders.
The plugin works with the Webpack standard [module types](https://webpack.js.org/guides/asset-modules/):
- asset/resource
- asset/inline
- asset
