### ISSUE TITLE
Integrity and Crossorigin attributes do not generate for Script tags

### ISSUE THREAD

**Issue by SteffenBlake** [webdiscus/html-bundler-webpack-plugin#43]
## Current behaviour

Setting `integrity` to `true` (or `auto` in production mode), does not cause the `integrity` or `crossorigin` attributes to get added to `<script>` tags.

## Expected behavior

The `integrity` and `crossorigin` attributes should be automatically applied to Scripts and Styles.

### Reproduction Example

Step 1: Checkout this repo and enable integrity
https://github.com/SteffenBlake/html-bundler-webpack-plugin-bug-examples/blob/29131635a37f9be1bd0e9187734d609d3178da99/webpack.config.js#L24

Step 2: Delete the following line to avoid reproducing the bug from #42 
https://github.com/SteffenBlake/html-bundler-webpack-plugin-bug-examples/blob/29131635a37f9be1bd0e9187734d609d3178da99/src/views/home.ejs#L3

Step 3: `npm run build` to compile the application

Step 4: Observe that `integrity` and `crossorigin` attributes are missing from the output html file

## Environment

- OS: Windows
- version of Node.js: v21.1.0
- version of Webpack: 5.89.0
- version of the Plugin: 2.15.0

**Comment by webdiscus** [comment]
Hello @SteffenBlake,

thanks for the issue report.
Yes, I can reproduce the bug.

## Workaround

Try to remove the `output.publicPath` option or set as `auto` or as the empty string:
- `publicPath: 'auto'`
- `publicPath: ''`

This is a bug, I will fix it for `publicPath: '/'` use case.

**Comment by SteffenBlake** [comment]
Looks like this is related to the same issue as #42 

Removing the `publicPath` property also causes the `crossorigin` and `integrity` attributes to start working.

Unfortunately for my use case I 100% need `publicPath` to be `/`, but hopefully that helps with sussing out the bug

**Comment by webdiscus** [comment]
The bug is fixed with `v2.15.1`.

**Comment by SteffenBlake** [comment]
Confirmed resolved in 2.15.1, thanks for the fix!
