### ISSUE TITLE
Disable url resolving 

### ISSUE THREAD

**Issue by andreivictor** [webdiscus/html-bundler-webpack-plugin#44]
Let's consider that in the `html` entry file there are some resources that should not be resolved by webpack - these resources will be placed in the `public` folder and copied in the dist folder with `webpack-copy-plugin.` 

To be more clear, the behaviour is similar with the `html-loader`  feature - https://github.com/webpack-contrib/html-loader#examples.

Is there any built-in option in this plugin? 

Thank you!

**Comment by webdiscus** [comment]
Hello @andreivictor,

to disable the resolving of URLs in all attributes, set the [sources](https://github.com/webdiscus/html-bundler-webpack-plugin#sources) option as `false`.

Or use the [filter](https://github.com/webdiscus/html-bundler-webpack-plugin#filter-function) of sources option to disable resolving an attribute by tag/attribute/value.

For example, the source script and style files in HTML should be resolved and processed, but all images are already coped via `copy-plugin` into `dist/` directory, then disable resolving only `src` attribute of image tag:

```js
new HtmlBundlerPlugin({
  entry: {
    index: 'src/views/index.html',
  },
  loaderOptions: {
    sources: [
      {
         tag: 'img',
         filter: ({ attribute }) => attribute !== 'src',
      }
    ],
  },
}),
```


The details see please in the [documentation](https://github.com/webdiscus/html-bundler-webpack-plugin#sources).

**Comment by webdiscus** [comment]
I don't use the comment like `<!-- webpackIgnore: true -->` to disable sources handling, because it's a bad idea.

**Comment by andreivictor** [comment]
Excellent! The `sources.filter` option is exactly what I needed. 

Thank you for your response.
