### ISSUE TITLE
Setting Root Public Path with more than 1 character breaks Integrity

### ISSUE THREAD

**Issue by SteffenBlake** [webdiscus/html-bundler-webpack-plugin#45]
## Current behavior

Integrity setting now works for a public path of `/`, but adding anything beyond that breaks it again producing the same errors as #42 and #43 (IE if your public path is `/test`

## Expected behavior

Complex Root Public Path should work with integrity

### Reproduction Example

https://github.com/SteffenBlake/html-bundler-webpack-plugin-bug-examples/blob/main/webpack.config.js#L32-L33

`npm run build` with current settings works and produces the expected output.

Switching the commented out `publicPath` config to be `/test` reproduces the bug.

## Environment

- OS: Windows
- version of Node.js: v21.1.0
- version of Webpack: 5.89.0
- version of the Plugin: 2.15.1

## Proposed Fix

Forking a branch, will be opening a PR shortly.

**Comment by webdiscus** [comment]
Hello @SteffenBlake,

thank you for the bugfix!
The `v2.15.2` fix is published.
