### ISSUE TITLE
Allow to pass minify options and set to auto

### ISSUE THREAD

**Issue by robinsonjohn** [webdiscus/html-bundler-webpack-plugin#5]
## Feature request

**What is motivation or use case for adding/changing the behavior?**

Minification is only desired when in production mode, and I would like to customize the default minification options.

As far as I can tell, there is no way to pass an object of custom objects and keep minification to auto/when only in production.

See: https://github.com/webdiscus/html-bundler-webpack-plugin#minify 

**Describe the solution you'd like**

Somehow combine `false`, `true` and `auto` with the configuration object.

**Comment by robinsonjohn** [comment]
@webdiscus That looks great to me, and I appreciate your making this plugin available.

**Comment by webdiscus** [comment]
@robinsonjohn 

in the version 1.12.0 is added the `minifyOptions` to set minification options when `minify` is `auto`

**Comment by robinsonjohn** [comment]
Perfect! Thank you for releasing and maintaining this plugin.

**Comment by webdiscus** [comment]
@robinsonjohn 

Thank you for very useful feature request.
Can the issue be closed?

**Comment by robinsonjohn** [comment]
I would say so from my end, thank you again.
