### ISSUE TITLE
installation error caused from installing favicon

### ISSUE THREAD

**Issue by Chidiro** [webdiscus/html-bundler-webpack-plugin#52]
i cant install the versions with built-in favicon plugin its giving me this `error`

`npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^>=7.1.4" of package "favicons@^>=7.1.4": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in: /Users/hamzaduras/.npm/_logs/2023-11-13T13_51_10_276Z-debug-0.log`

- Macos sanoma 14.1.1
- version of Node.js: 21.1.0
- version of Webpack: 5.89.0
- version of the Plugin: 3.0.1 & 3.0.0

**Comment by webdiscus** [comment]
Hello @Chidiro,

thanks for the issue report!
I will fix it now.

**Comment by webdiscus** [comment]
@Chidiro 

please, use the fixed version `v3.0.3`.

Thank You!
