### ISSUE TITLE
[FEATURE REQUEST] Support the CSS extraction from styles used in *.vue files

### ISSUE THREAD

**Issue by else1fy** [webdiscus/html-bundler-webpack-plugin#53]
## Current behaviour

Build time is incredibly increased if there is an import of vue sfc components in the code, from 4 seconds to 80. If there is a link to the style file in this component, then the project is not built and crashes with an error.

### Reproduction Example

I used vue-loader for processing sfc components, swc-loader for js/ts files and sass-loader for style files. And of course your plugin, if you remove it from the configuration and transfer only the ts file to webpack, everything works as expected

## Environment

- OS: Linux
- version of Node.js: 18.18.2
- version of Webpack: 5.89.0
- version of the Plugin: 3.0.3

## Additional context

After digging a little in the code, putting console.log wherever possible, I got to this place Collection->findDependenciesOfModule->walk, it looks like this function gets into some kind of infinite recursion, I may be wrong, but I hope it helps you somehow

**Comment by webdiscus** [comment]
Hello @else1fy,

thanks for the issue report.
I don't use vue, can you please create a small repo with reproducible issue.

**Comment by webdiscus** [comment]
The html-bundler-webpack-plugin is designed as replacer of the html-webpack-plugin.
As far as I know, Vue is mostly used with Vite.

**Comment by else1fy** [comment]
Hello @webdiscus,

I switched to webpack and your plugin because Vite does not give me the same flexibility in terms of the structure of files/folders in dist as webpack, it decides a lot for me, and I can't influence it, and this is very important in my work

I was not able to reproduce a serious increase in build time in a minimal configuration, I will try to understand what is the matter a little later. In the current repository, I reproduced an error with connecting a scss file inside the sfc component

https://github.com/else1fy/html-bundler

**Comment by webdiscus** [comment]
@else1fy thanks for the repo. I try to fix it.

As a workaround, you can defile the SCSS file directly in HTML, not in *.vue file, because the plugin works with scripts (js, ts, mjs, etc.). But I'm trying to extend functionality for vue.

**Comment by else1fy** [comment]
> @else1fy thanks for the repo. I try to fix it.
> 
> As a workaround, you can define the SCSS file directly in HTML, not in *.vue file, because the plugin works with scripts (js, ts, mjs, etc.). But I'm trying to extend functionality for vue.
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
>     <head>
>         <meta charset="UTF-8">
>         <meta name="viewport" content="width=device-width, initial-scale=1.0">
>         <title>Home</title>
>        
>         <link href="./MyButton.scss" rel="stylesheet" />
>     </head>
>     <body>
>         <div id="app">
>             <h1>{{ title }}</h1>
>             <my-button></my-button>
>         </div>
>         <script src="./index.ts"></script>
>     </body>
> </html>
> ```

Thanks for the suggestion, I thought about it, but the first thing that came to my mind was that importing dozens or even hundreds of component style files into an html file is too much.

But taking another look at your example, now I think it's possible to import all these files into one other style file, and plugging it into html could be the solution.

And yet, I would like to be able to keep the components completely isolated, so that by importing just one file, we would pull all its dependencies, including styles.

**Comment by else1fy** [comment]
I was able to reproduce the build time increase (~10 times), this happens when we import any style file directly into the ts file into which the sfc vue component is imported.

You can view all this in the same repository, in the "build time" branch.

**Comment by webdiscus** [comment]
> importing dozens or even hundreds of component style files into an html file is too much.

Yes you are right.

> import all these files into one other style file, and plugging it into html 

This is the fastest way, the plugin does not have to recursively find a parent module.

> I would like to be able to keep the components completely isolated, so that by importing just one file, we would pull all its dependencies, including styles

Yes, that makes sense.
I'll try to add support for Vue, but it is not easy.
The current version can extract imported styles from JS/TS files.

**Comment by webdiscus** [comment]
@else1fy can you please test the beta version `3.1.0-beta.0`

- added support of extract CSS from styles imported in *.vue

This is only beta version to test. The build time of the example "Hello World" it tooo long, ~ 1 sec, because the Webpack generate tooo much needles dependency modules for each Vue runtime component :-/

**Comment by webdiscus** [comment]
@else1fy 

I have tested the `v3.1.0-beta.0` with both branches the `main` and `build-time`. The build time is the same: ~ 1-1.3 sec.

if I open the compiled html in a browser, I see empty page.

The generated html contains div with tags:
```html
      <div id="app">
            <h1>{{ title }}</h1>
            <my-button></my-button>
        </div>
```

In the  browser inspector is:
```html
<div id="app" data-v-app=""><!----></div>
```

So the Vue app replaces the div#app with empty string. What's wrong? Why can't I see "Hello World?"

**Comment by else1fy** [comment]
There are a couple of points

1. For some reason, when I install the beta version and try to build it, it gives an error. But it disappears if you delete the node_modules folder and the package-lock.json file, and re-run npm i
![image_2023-11-20_15-12-34](https://github.com/webdiscus/html-bundler-webpack-plugin/assets/103573216/b309d4f4-74e5-468a-b2b3-7a822e94023d)
2. If you specify the language of the style file using the lang="scss" attribute, it also gives an error
![image_2023-11-20_15-22-18](https://github.com/webdiscus/html-bundler-webpack-plugin/assets/103573216/27198d85-7ab4-4077-9e17-d41b408d72f9)

**Comment by else1fy** [comment]
> @else1fy
> 
> I have tested the `v3.1.0-beta.0` with both branches the `main` and `build-time`. The build time is the same: ~ 1-1.3 sec.
> 
> if I open the compiled html in a browser, I see empty page.
> 
> The generated html contains div with tags:
> 
> ```
>       <div id="app">
>             <h1>{{ title }}</h1>
>             <my-button></my-button>
>         </div>
> ```
> 
> In the browser inspector is:
> 
> ```
> <div id="app" data-v-app=""></div>
> ```
> 
> So the Vue app replaces the div#app with empty string. What's wrong? Why can't I see "Hello World?"

This is because I did not specify a special alias for vue, I fixed it in the main branch, I also added the lang="scss" attribute there, which causes an error during the build. If you remove it and build it, then index.html in dist should display the content as expected

**Comment by webdiscus** [comment]
> delete the node_modules folder and the package-lock.json file, and re-run npm i

I can't reproduce it. By me local works w/o error.

> If you specify the language of the style file using the lang="scss" attribute, it also gives an error

yes, I can reproduce it. W/o the `lang` attribute works fine, but with the attribute  it gives an error.
Just added an attribute total breaks the workflow of inner processes in Webpack :-/ I try to fix it.

**Comment by webdiscus** [comment]
> If you specify the language of the style file using the lang="scss" attribute, it also gives an error

ah, I have read the vue [docu](https://vue-loader.vuejs.org/guide/pre-processors.html#sass).

If you add the `lang` attribute, then will be applied the sass loader to the resource.
The `lang` attribute should be added  only when no html bundler plugin used, because the bundler plugin self resolve the source SCSS file and apply own style loader.

Also, it makes no sense to use  `lang="scss"` attribute in vue, just remove it, the plugin does it for you.

**Comment by webdiscus** [comment]
@else1fy 

in the `v3.1.0-beta.0` is fixed issue when using the `lang="scss"` attribute.
So, using the html bundler plugin, the lang="scss" attribute is not needed, it takes no effect.
For the compatibility with existing components, which already have the `lang` attribute , this attribute will be in the plugin ignored.

**Comment by else1fy** [comment]
@webdiscus Yes, it works, thanks a lot!

Now I don’t have the opportunity to test this assembly on a full-fledged project, but it will be tomorrow. At first glance there shouldn't be any problems)

You've made an amazing plugin, keep it up!

**Comment by webdiscus** [comment]
@else1fy  thank you for the very interesting use case :-)

**Comment by else1fy** [comment]
@webdiscus There is one more point: styles written directly in the <style> tag are not extracted into a separate file. The vue-loader documentation says to use mini-css-extract-plugin, but as I understand it, this is not possible with the html bundler plugin. Updated the main branch of the repository

**Comment by else1fy** [comment]
I also discovered that these styles are not added to the page at startup, apparently you need a vue-style-loader for this. But when I try to add it to the chain, the build crashes with an error.
![image_2023-11-21_10-52-34](https://github.com/webdiscus/html-bundler-webpack-plugin/assets/103573216/691443c6-efd8-45fb-bc8a-57e26e6021ba)

This was circumvented using the rules specified specifically for styles from sfc vue components.
![image_2023-11-21_10-56-41](https://github.com/webdiscus/html-bundler-webpack-plugin/assets/103573216/2ed02782-691b-4d9b-a680-df13793ab1d6)

**Comment by else1fy** [comment]
I don’t really use this functionality in my work, so it’s not critical for me, but it’s probably worth considering these points (in the future?) to more fully support the style functionality.

**Comment by webdiscus** [comment]
> styles written directly in the <style> tag 

This is a very strange (idea/feature of Vue) :-), but very interesting and important use case. I'm in the process...


Both: `mini-css-extract-plugin` and `vue-style-loader` must not be used with the bundler plugin, because:

- the bundler plugin 120% replaces the functionality of the `mini-css-extract-plugin`
- the `vue-style-loader` is the fork of the `style-loader` and the bundler plugin can do the same (inline CSS into HTML),
  but the bundler plugin can't (yet) HMR (update CSS w/o reloading) of style, this feature is missing, sorry :-(
- the bundler plugin uses own `CSS extractor` as endpoint loader,  so the `mini-css-extract-plugin` and `vue-style-loader` can't be used together with the plugin, all do the same

**Comment by else1fy** [comment]
> the vue-style-loader is the fork of the style-loader and the bundler plugin can do the same (inline CSS into HTML),

But if you remove vue-style-loader from the chain, then although the css code appears in the bundle file, when you open the page in the browser, it is not added to the dom, you can try this in the repository

**Comment by webdiscus** [comment]
HTML bundler plugin designed for working with normal templating engines (pug, hbs, ejs, etc.) but not for vue, react, etc, therefore initially the plugin can't support non-standard strange framework-specifically features ;-)
Firstly it must be implemented in the plugin.

So, the plugin can inline CSS into HTML when the style files specified directly in HTML or styles imported in JS/TS. See please [How to inline CSS in HTML](https://github.com/webdiscus/html-bundler-webpack-plugin/issues/53#recipe-inline-css).

In your case: (S)CSS -> <style> -> Vue -> TS -> HTML. This is Vue-specifically use case. Of course, the plugin knows nothing about this. The support of this must be implemented extra in the plugin. 
I'm in process to do this ;-)

**Comment by webdiscus** [comment]
@else1fy 

good news, following already works by me local:
```html
<style module>
button {
  background-color: wheat;
}
</style>
```

The CSS will be extracted into separate *.css file.

I must yet to implement for the following cases:
```html
<style>
/* global styles */
</style>

<style scoped>
/* local styles */
</style>
```

Vue do mishmash of loaders for each use case, with absolutely different sets. I must filter each case separately :-/

**Comment by webdiscus** [comment]
@else1fy 

try please `3.1.0-beta.3`

**Comment by webdiscus** [comment]
you can inline CSS using the `css.inline` option:

```js
new HtmlBundlerPlugin({
      entry:'src/pages/',
      css: {
        inline: true, // 'auto' - in development mode adds to DOM, in production mode - stores as a file
      },
    })
```

**Comment by else1fy** [comment]
@webdiscus Yes, extracting styles from the <style> tag of a component's sfc into a separate file works. Modules cannot be used, since classes are not added to the element, scoped has no effect

**Comment by webdiscus** [comment]
ok, then I can release this feature.

**Comment by else1fy** [comment]
Yes, great job, thank you very much!)

**Comment by webdiscus** [comment]
the support for styles in `*.vue` files is released in the version `3.1.0`

Thank you for the very useful feature request!

Can be the issue closed?

---

P.S.:
I'm not a Vue developer and don't know where to "promote" this useful plugin for Vue developers.
On reddit are very toxic admins, all my posts was immediately deleted :-/

**Comment by else1fy** [comment]
@webdiscus I’m also not sure about resources for promotion, but if necessary, I will definitely recommend your plugin to my colleagues)

By the way, in the new version it looks like there is a typing error; the `test` field is required in the `js` plugin configuration

**Comment by webdiscus** [comment]
@else1fy 

> a typing error; the test field is required in the js plugin configuration

I have fixed the `js.test` option in the version `3.1.1`. This is undocumented option for debugging and should not be used.

>  I’m also not sure about resources for promotion

thanks, you can forget about it.
I would just like to share information about this plugin with other developers. Perhaps this plugin can be useful to many.

P.S.:

I developed this bundler plugin to make building my work projects much easier.

Before, I, like everyone else, used the `html-webpack-plugin` with great pain and blood in my eyes, since there were no alternatives (yes, now there are Parcel and Vite).
This `html-webpack-plugin` is a `big crutch`, and not a sane solution. The _"chunks-hell"_ alone (which js/css to inject into which html) is worth it.

Therefore, I decided to create the right plugin with a natural approach to solving the problem.
