### ISSUE TITLE
Ignored imports (where an alias is set to `false`) causes error

### ISSUE THREAD

**Issue by davidmurdoch** [webdiscus/html-bundler-webpack-plugin#56]
```
ERROR in [entry] [initial]
Cannot read properties of undefined (reading '_bundlerPluginMeta')
TypeError: Cannot read properties of undefined (reading '_bundlerPluginMeta')
    at walk (/home/david/code/metamask-extension2/node_modules/html-bundler-webpack-plugin/src/Plugin/Collection.js:529:67)
```

https://github.com/webdiscus/html-bundler-webpack-plugin/blob/d278fced2903c68dbebd7de8c76907baea621d8c/src/Plugin/Collection.js#L536

I think the fix might be to check if `depModule.resourceResolveData` is defined before continuing to walk the dependencies.

p.s., The `// TODO: test` existing on the same line as the failing code made me smile a little :-)

**Comment by davidmurdoch** [comment]
Nevermind, adding `if (!depModule.resourceResolveData) continue;` just causes:

```
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
```

**Comment by webdiscus** [comment]
@davidmurdoch 

can you please share your use case. I need it to write the test for this issue.

**Comment by davidmurdoch** [comment]
I'll try to get something together next week.

**Comment by webdiscus** [comment]
the `resolve.extensions = ['.scss', '.ts', '.js']` is a wrong config, you should auto resolve only `.js`, `.ts` files, but not `.scss`.
If you use `resolve.extensions = ['.ts', '.js']` only does the error occur?

**Comment by davidmurdoch** [comment]
Yeah, sorry I wasn't clear. Removing `.scss` from `resolve.extensions` seems to have been the fix for this, as well as some other import issues I was having.

My hunch was that multiple files with the same name, but different extensions (that webpack will resolve), causes some condition that causes a circular `walk` in this plugin. I suspect a ts file and a js file with the same name will cause the issue as well, but I haven't tried creating a minimal reproduction.

**Comment by webdiscus** [comment]
@davidmurdoch  can be the issue closed? The solution was not using style extensions in the `resolve.extensions`.

**Comment by davidmurdoch** [comment]
> Can be the issue closed? The solution for the circular walk was not using style extensions in the resolve.extensions.

I don't mind if you close it. But I do think this case should be handled somehow, maybe even just with some documentation about how to do things correctly, like you have for `splitChunks` (thank you for that! it was so helpful!).

**Comment by webdiscus** [comment]
@davidmurdoch 

I have added in the readme the new section [Automatic resolving of file extensions](https://github.com/webdiscus/html-bundler-webpack-plugin#automatic-resolving-of-file-extensions) under **Problems & Solutions**.

You can correct and supplement the text. Any PR is welcome!

**Comment by davidmurdoch** [comment]
Perfect! You're a really great FOSS maintainer. Thanks once again!

**Comment by webdiscus** [comment]
> Perfect! You're a really great FOSS maintainer. Thanks once again!

If you think this plugin could be useful to other developers, perhaps you can (but not must) promote it on your Twitter and/or Reddit ;-)
