### ISSUE TITLE
Mix use entry in plugin and in webpack

### ISSUE THREAD

**Issue by dawnchan030920** [webdiscus/html-bundler-webpack-plugin#58]
## Mix use entry in plugin and in webpack
I want to take advantage of the recursive entries in the plugin config which is very convenient, but I also have non-html entry points that I want to specify in webpack-level entry field. I'm wondering what is the best practice to do so.
It would be very nice if anyone can guide me over that.

**Comment by webdiscus** [comment]
Hello @dawnchan030920,

you can use default Webpack entry for your JS/CSS entires:

```js
module.exports = {
  mode: 'production',

  output: {
    path: path.join(__dirname, 'dist/'),
  },

  entry: {
    main: './src/main.js', // => dist/js/main.js
    style: './src/styles.scss', // => dist/css/style.css
  },

  plugins: [
    new HtmlBundlerPlugin({
      entry: {
        index: 'src/views/index.html', // => dist/index.html
      },
      js: {
        // output filename for JS files defined in webpack.entry and in html
        filename: 'js/[name].js',
      },
      css: {
        // output filename for CSS files defined in webpack.entry and in html
        filename: 'css/[name].css',
      },
    }),
  ],

  module: {
    rules: [
      {
        test: /\.(s?css)/,
        use: ['css-loader', 'sass-loader'],
      },
    ],
  },
};
```

**Comment by webdiscus** [comment]
> advantage of the recursive entries in the plugin
what do you mean? An example?

**Comment by dawnchan030920** [comment]
> > advantage of the recursive entries in the plugin
> 
> what do you mean? An example?

keep the directory strcucture

> > I have non-html entry points
> 
> I can only imagine one use case: if you build a css/js package to use as a library.

I want to transform markdown files using remark-loader and the loader this plugin

**Comment by webdiscus** [comment]
@dawnchan030920 

can you please create small repo with minimum required files (html, *.md, js, css, webpack.config.js, ...) then I can help you.

**Comment by dawnchan030920** [comment]
Sorry for being unclear about my question and providing little information😭
[the minimal example](https://stackblitz.com/edit/stackblitz-starters-hf9qib?file=index.js)
I'm wondering if I could set entry in plugin's option to bundle all html files under src and set entry in webpack to specify the markdown as entry.
Thank you for your patient answering!

**Comment by webdiscus** [comment]
@dawnchan030920 

the `Webpack.entry` and `plugin.entry` is the same place with the same structures.
But only in `plugin.entry` you can provide template variables, because the original `Webpack.entry` structure doesn't this feature. Also, the `plugin.entry` is the same `Webpack.entry` `+` the [data](https://github.com/webdiscus/html-bundler-webpack-plugin#advanced-syntax) option to pass external variables into the template.

**Comment by dawnchan030920** [comment]
Thank you for your explanation.
