### ISSUE TITLE
How to use twig template, I tried to develop according to example, but it doesn't work

### ISSUE THREAD

**Issue by leolilac** [webdiscus/html-bundler-webpack-plugin#63]
How to use twig template, I tried to develop according to example, but it doesn't work.
Looking forward to your reply, thanks.

[Code Link](https://stackblitz.com/edit/webpack-webpack-js-org-dbjy66?file=src%2Fviews%2Fpages%2Findex.twig)

**Comment by webdiscus** [comment]
Hello @leolilac,

your `partials/layout.twig` file uses `tabs`, therefore the `twigjs` can't compile this template. Please reformat the template using `spaces`. 

Try run the working example [Twig with Webpack](https://stackblitz.com/edit/twig-webpack?file=webpack.config.js).

**Comment by leolilac** [comment]
已收到，谢谢
