### ISSUE TITLE
Process asset references in meta tags

### ISSUE THREAD

**Issue by gpoitch** [webdiscus/html-bundler-webpack-plugin#7]
## Current behaviour

Image url references in a meta tag aren't processed to the output directory.

## Expected behaviour

meta tags are processed the same as img, link, etc.

### Reproduction Example

```html
 <meta property="og:image" content="../assets/og.png" />
```

## Environment

- OS: macOS
- version of Node.js: 19.6.1
- version of Webpack: 5.77.0
- version of the Plugin: 1.13.0

## Additional context

If I put the same url in a img tag: ` <img src="../assets/og.png" />` it gets processed so im guessing it's trying to parse specific tags? Haven't dug through the source code yet.

Using EJS if that matters.

**Comment by gpoitch** [comment]
I found how to do this in the documentation.
Perhaps consider making this a default.
Thanks!

**Comment by gpoitch** [comment]
Yes, I was able to use the filter function. I wouldn't add more API surface for this. I would try to just process any relative urls in meta content.

**Comment by webdiscus** [comment]
@gpoitch 

thanks for the answer!
