### ISSUE TITLE
Inline not working with minify

### ISSUE THREAD

**Issue by gpoitch** [webdiscus/html-bundler-webpack-plugin#8]
## Current behaviour

When enabling minify, style and scripts are not inlined properly

## Expected behaviour

style and scripts are inlined properly with minify on

### Reproduction Example

```js
new HtmlBundlerPlugin({
  minify: true,
  js: {
    inline: true
  },
  css: {
    inline: true
  }
})
```

Page:
```html
<script src="./script.js"></script>
<link rel="stylesheet" href="./style.css" />
```

Output:
Script contains the path, style is empty.
```html
<script>path,to,my,script.js</script>
<style></style>
```

If I disable minify, it inlines correctly.

## Environment

- OS: macOS
- version of Node.js: 19.6.1
- version of Webpack: 5.78.0
- version of the Plugin: 1.15.0

**Comment by webdiscus** [comment]
Hello @gpoitch ,

thanks for the issue report.
I will fix it.

**Comment by webdiscus** [comment]
@gpoitch 

in the release 1.16.0 this bug is fixed

**Comment by gpoitch** [comment]
Working. Thanks!
