### ISSUE TITLE
Commented-out Stylesheet Links Still Throw Compiler Errors

### ISSUE THREAD

**Issue by DylanVause** [webdiscus/html-bundler-webpack-plugin#84]
## Current behaviour

My HTML page contains the following line:

```html 
<!-- <link rel="stylesheet href="MyStyles.css" /> -->
```

I do not have a file named MyStyles.css, and so the plugin reports errors in finding MyStyles.css.

## Expected behaviour

The plugin should ignore all HTML lines that are comments.  It should not try to resolve references enclosed in comments.

## Environment

- OS: Windows
- version of Node.js: v18.17.1
- version of Webpack: 5.89.0
- version of the Plugin: 3.6.5

**Comment by webdiscus** [comment]
Hello @DylanVause,

> The plugin should ignore all HTML lines that are comments. It should not try to resolve references enclosed in comments.

The plugin uses very fast and simple parser for references in tag attributes.
Determining whether a tag is commented out is a complex and slow operation.

## Workaround

To disable parsing of an default attribute, just add to the attribute name a prefix, e.g. `href ` -> `x-href `:
```html
<!-- <link rel="stylesheet x-href="MyStyles.css" /> -->
```

P.S.: this is the duplicate issue, see the same case by #41

**Comment by webdiscus** [comment]
Hello @FlorentMasson,

this is not an issue, this is a feature :-)
We wan't use very heavy jsdom. It's too slow and too big, over 3 MB.

For the "issue" there is a "workaround".

**Comment by webdiscus** [comment]
@DylanVause, @FlorentMasson 

I found a solution to commented out one or more tags without resolving.

By defaults is used the `Eta` templating engine, therefore you can use the templating comments `<%/* ... */%>`:

```html
<html>
  <head>
    <title>Test</title>
    <%/* <link rel="stylesheet href="MyStyle.css" /> Single line comment w/o resolving */%>
  </head>
  <body>
    <h1>Hello World!</h1>
    <%/*
      Multi line comment w/o resolving
      <img src="./image1.png" />
      <img src="./image2.png" />
    */%>
  </body>
</html>
```

## Note

If you use a [templating engine](https://github.com/webdiscus/html-bundler-webpack-plugin#template-engine) then should be used  engine specific comment
