### ISSUE TITLE
[QUESTION] Markdown files with handlebars

### ISSUE THREAD

**Issue by Paillat-dev** [webdiscus/html-bundler-webpack-plugin#96]
My question is: is it possible to use markdown and have it turned into html, then used in a handlebars template with layouts?
For example:
```md
{{#partial 'content'}}
# Heading 1
Bla bla bla
- 1
- 2
- 3
{{/partial}}
{{> myTemplate}}
```

**Comment by webdiscus** [comment]
I think, it is possible using a helper that compiles partials containing MD content.
But I'm not sure whether such helper exists.

To render markdown files into HTML I use the [pug-plugin](https://github.com/webdiscus/pug-plugin) which has build-in [:markdown](https://github.com/webdiscus/html-bundler-webpack-plugin/issues/96#filter-markdown) filter. This filter supports the syntax highlighting, see the [:markdown examples](https://webdiscus.github.io/pug-loader/pug-filters/markdown.html).

**Comment by webdiscus** [comment]
I found the [helper-markdown](https://github.com/helpers/helper-markdown?tab=readme-ov-file#handlebars) for handlebars.

**Comment by Paillat-dev** [comment]
```js
const markdown = require('helper-markdown');
[...]
    preprocessorOptions: {
      partials: ['src/views/partials/', 'src/views/pages/'],
      helpers: {
        markdown,
      },
    }
```

```
npm install --dev helper-markdown
```

```handlebars
{{#markdown}}
# Heading
bleh blah

{{/markdown}}
```
