### ISSUE TITLE
[QUESTION] Include javascript file generated by babel-loader/ts-loader

### ISSUE THREAD

**Issue by R1kk3r** [webdiscus/html-bundler-webpack-plugin#98]
I have an index.ts and because I am targeting super old browsers, I need to:
- Convert TS to JS via ts-loader
- The newly generated JS is passed to babel-loader to make it compatible with chrome 37 
- Some dependencies needs to be made compatible with chrome 37 via babel-loader
- Include `whatwg-fetch` to have a polyfill for the fetch API.
- The output is a `main.js` file.

I would like to use HtmlBundlerPlugin but I cannot figure out how to tell him to include the resulting main.js. Doing something like this
```html
<script src="dist/main.js"r></script>
```
will return the following error

```
...
HTML Bundler Plugin  Resolving of source files in the template file failed.
File: src/views/mytemplate.eta
Error: Cannot find module '/Users/xxx/yyy/ccc/repo/dist/main.js'
```

It seems everything is generated at the same time and the main.js is not yet outputted into /dist/.

Any idea how I can fix this?

My current webpack config generating the main.js.
```js
entry: ['whatwg-fetch', './src/index.ts'],
resolve: {
  extensions: [ '.ts', '.js'],
},
module: {
    rules: [
     {
         test: /\.js$/,
         include:[
             /node_modules\/\@aaaa/,
             /node_modules\/\@bbbb/,
         ],
         use: [{
          loader: 'babel-loader',
          options: {
            presets: [
              ['@babel/preset-env', { targets: "chrome 37", useBuiltIns: "usage", modules:"cjs", corejs:3, debug:false}]
            ]
          }
        }]
     },
      {
        test: /\.ts$/,
        exclude: [
          path.resolve(__dirname, 'tests')
        ],
        use: [{
          loader: 'babel-loader',
          options: {
            presets: [
              ['@babel/preset-env', { targets: "chrome 37", debug:false}]
            ]
          }
        },
        {
        loader: 'ts-loader',
        }
     ]
    }
    ],
  },
  target: ['es5', 'web'],
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
```

**Comment by webdiscus** [comment]
@R1kk3r 

you should specify the source `./src/index.ts` file directly in the template using the relative path or webpack alias:

```html
<script src="./index.ts"r></script>
```

The plugin resolves source files of assets (SCSS, TS/JS, etc.) in templates and replaces them with correct output URLs in the generated HTML. 

Don't needed to define source TS files in webpack entry.
Read please the README. All information with examples is there.

You can create a small repo with your setup and I will help you to configure it.
